name: manual
on: workflow_dispatch
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: manual
        run: |
          IFS='.' read -r version1 version2 <<< "2.0"
          if [[ ${{vars.major}} -gt $version1 ]]; then
            echo "inside if"
          else
            echo "inside else"
          fi
