name: one
on: pull_request
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: |
          if [[ ${{ github.head_ref == 'feature1' && ${{ github.base_ref == 'dev' }} ]];then
            echo "target branch is dev"
          fi
            
