name: tmp
on: push
jobs:

  paramters:
    runs-on: ubuntu-latest
    outputs:
      n: ${{ steps.param.ouputs.n }}
      l: ${{steps.param.ouputs.l}}
    steps:
      - name: param
        run: |
          echo "n=rajatenv" >> $GITHUB_OUTPUT
          echo "l=bhawsarenv" >> $GITHUB_OUTPUT
      - name: useparam
        run: |
          echo ${{needs.parameters.outputs.n}}, ${{needs.parameters.outputs.l }}
  param_jobs:
    needs: paramters
    runs-on: ubuntu-latest
    env:
      
    steps:
      - name: using_param_job
        run: |
          echo $n,$l
  tmp:
    runs-on: ubuntu-latest
    steps:
      - name: tmp_step
        run: |
          echo ${{vars.MAJOR_RELEASE_VERSION }}
  tmp_env:
    runs-on: ubuntu-latest
    env:
      name: rajat
      lastname: bhawsar
    steps:
      - name: env_tmp_task
        run: |
          echo $name,$lastname
          echo ${{env.name }} ${{env.lastname}}

      
